parser:
  language: "en"
  api_key_env: "LLAMA_CLOUD_API_KEY"
  chunk_size: 1500
  chunk_overlap: 200

extractor:
  openai_model: "gpt-3.5-turbo"
  schema_path: "./schemas/statement.json"
  api_key_env: "OPENAI_API_KEY"

qa_generator:
  openai_model: "gpt-3.5-turbo"
  temperature: 0.0
  max_tokens: 256
  batch_size: 5
  api_key_env: "OPENAI_API_KEY"

export:
  content_path: "./output/content.json"
  qa_jsonl_path: "./output/qa.jsonl"
